site_name: patrislav's blog
site_author: Patrick Huesmann <patrick@p-hu.de>
site_url: https://www.p-hu.de
copyright: Copyright 2024 Patrick Huesmann

plugins:
  - search
  - blog:
      blog_dir: .

theme:
  name: material
  language: en # The language your site is written in
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Automatic mode (use system preference)
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Light mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Dark mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/mastodon 
      link: https://chaos.social/@patrislav
    - icon: fontawesome/brands/github
      link: https://github.com/patrislav1
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/patrickhuesmann/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/patrickhuesmann/

